sherpany/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts.views import RegisterView

app_name = "accounts"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
]

sherpany/events/urls.py
from django.urls import path

from events.views import (
    CreateUpdateEventView,
    DeleteEventView,
    DetailEventView,
    MyEventView,
    PublicEventView,
    ReserveEventView,
    WithdrawReservationEventView,
)

app_name = "event"

urlpatterns = [
    path("", MyEventView.as_view(), name="my_events"),
    path("create/", CreateUpdateEventView.as_view(), name="create_event"),
    path(
        "<int:pk>/",
        DetailEventView.as_view(),
        name="detail_event",
    ),
    path(
        "<int:pk>/update/",
        CreateUpdateEventView.as_view(),
        name="update_event",
    ),
    path("<int:pk>/delete/", DeleteEventView.as_view(), name="delete_event"),
    path("public/", PublicEventView.as_view(), name="public_events"),
    path(
        "<int:pk>/reserve/",
        ReserveEventView.as_view(),
        name="reserve_event",
    ),
    path(
        "<int:pk>/withdraw-reservation/",
        WithdrawReservationEventView.as_view(),
        name="withdraw_event_reservation",
    ),
]

sherpany/sherpany/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("accounts:login"))),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("events/", include("events.urls", namespace="events")),
]

sherpany/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager as DefaultUserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _


class UserManager(DefaultUserManager):
    """Custom User Manager."""

    def create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User, automatically fills 'username' as email
        """
        return super(UserManager, self).create_user(
            email=email, username=email, password=password, **extra_fields
        )


class User(AbstractUser):
    """Custom User Model."""

    email = models.EmailField(_("email address"), unique=True)
    objects = UserManager()

sherpany/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from accounts.models import User


class RegisterUserForm(UserCreationForm):
    """Override UserCreationForm to use email."""

    class Meta:
        model = User
        fields = ("email",)

    def save(self, commit=True):
        """Override save method to set username as email."""
        user = super().save(commit=False)
        user.username = self.cleaned_data.get("email")
        user.set_password(self.cleaned_data.get("password1"))
        if commit:
            user.save()

        return user

sherpany/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from accounts.forms import RegisterUserForm


class RegisterView(CreateView):
    form_class = RegisterUserForm
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/register.html"

sherpany/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <form action="{{request.path}}" method="POST">
      {% csrf_token %}
      {% if form.errors %}
        <div class="m-alert m-alert--outline alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
            <span>Incorrect email or password. Please try again.</span>
        </div>
      {% endif %}
      <div class="form-group col-md-3">
        <label>Email</label>
        <input class="form-control m-input" type="text" name="username" autocomplete="off">
      </div>
      <div class="form-group col-md-3">
        <label>Password</label>
        <input class="form-control m-input m-login__form-input--last" type="password" name="password">
      </div>
      <button type="submit" class="btn btn-primary">Login</button>
      <a href="{% url 'accounts:register' %}">Register</a>
  </form>
{% endblock content %}

sherpany/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
  <form action="{{request.path}}" method="POST">
      {% csrf_token %}
      {% if form.errors %}
        <div class="m-alert m-alert--outline alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
            <span>Please correct your data and try again.</span>
        </div>
      {% endif %}
      {{form.as_p}}
      <button type="submit" class="btn btn-primary">Register</button>
  </form>
{% endblock content %}