sherpany/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts.views import RegisterView

app_name = "accounts"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
]

sherpany/events/urls.py
from django.urls import path

from events.views import (
    CreateUpdateEventView,
    DeleteEventView,
    DetailEventView,
    MyEventView,
    PublicEventView,
    ReserveEventView,
    WithdrawReservationEventView,
)

app_name = "event"

urlpatterns = [
    path("", MyEventView.as_view(), name="my_events"),
    path("create/", CreateUpdateEventView.as_view(), name="create_event"),
    path(
        "<int:pk>/",
        DetailEventView.as_view(),
        name="detail_event",
    ),
    path(
        "<int:pk>/update/",
        CreateUpdateEventView.as_view(),
        name="update_event",
    ),
    path("<int:pk>/delete/", DeleteEventView.as_view(), name="delete_event"),
    path("public/", PublicEventView.as_view(), name="public_events"),
    path(
        "<int:pk>/reserve/",
        ReserveEventView.as_view(),
        name="reserve_event",
    ),
    path(
        "<int:pk>/withdraw-reservation/",
        WithdrawReservationEventView.as_view(),
        name="withdraw_event_reservation",
    ),
]

sherpany/sherpany/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("accounts:login"))),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("events/", include("events.urls", namespace="events")),
]

sherpany/templates/base.html
<html>
  <title>Sherpany Event</title>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    {% block extra_css %}
    {% endblock extra_css %}
  </head>
  <body>
    {% if messages %}
      {% for message in messages %}
        <div class="col-sm-12 col-md-12 col-xl-8">
          <div class="alert {% if message.tags == 'success' %}alert-success background-success{% else %}alert-danger background-danger{% endif %} icons-alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <i class="icofont icofont-close-line-circled"></i>
            </button>
            <p><strong>{{ message }}</strong></p>
          </div>
        </div>
      {% endfor %}
    {% endif %}

    {% if request.user.is_authenticated %}
      <a href="{% url 'accounts:logout' %}">Logout</a>
      {% include 'navigation.html' %}
    {% endif %}

    {% block content %}

    {% endblock content %}
  </body>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
  <script>
    $(document).ready(function(){
      $('.post_link').click(function(event){
            event.preventDefault();
            var link = $(this).attr('href');
            var confirm_message = $(this).attr('confirm_message');
            if (confirm(confirm_message)){
              var $form = $('<form method="post" action="' + link + '"></form>');
              $form.append('<input type="hidden" name="csrfmiddlewaretoken" value="' + document.cookie.match(/csrftoken=(\w+)/)[1] + '" />');

              $($(this)[0].attributes).each(function(){
                  $form.append('<input type="hidden" name="' + this.nodeName + '" value="' + this.nodeValue+ '"/>');
              })
              $form.appendTo($('body')).submit();
            }

            return;
        })
    })
  </script>
  {% block extra_js %}
  {% endblock extra_js %}
</html>

sherpany/templates/navigation.html
<a href="{% url 'events:my_events' %}" class="btn btn-success">My Events</a>
<a href="{% url 'events:create_event' %}" class="btn btn-success">Create Event</a>
<a href="{% url 'events:public_events' %}" class="btn btn-primary">Public Events</a>