sherpany/events/urls.py
from django.urls import path

from events.views import (
    CreateUpdateEventView,
    DeleteEventView,
    DetailEventView,
    MyEventView,
    PublicEventView,
    ReserveEventView,
    WithdrawReservationEventView,
)

app_name = "event"

urlpatterns = [
    path("", MyEventView.as_view(), name="my_events"),
    path("create/", CreateUpdateEventView.as_view(), name="create_event"),
    path(
        "<int:pk>/",
        DetailEventView.as_view(),
        name="detail_event",
    ),
    path(
        "<int:pk>/update/",
        CreateUpdateEventView.as_view(),
        name="update_event",
    ),
    path("<int:pk>/delete/", DeleteEventView.as_view(), name="delete_event"),
    path("public/", PublicEventView.as_view(), name="public_events"),
    path(
        "<int:pk>/reserve/",
        ReserveEventView.as_view(),
        name="reserve_event",
    ),
    path(
        "<int:pk>/withdraw-reservation/",
        WithdrawReservationEventView.as_view(),
        name="withdraw_event_reservation",
    ),
]

sherpany/sherpany/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("accounts:login"))),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("events/", include("events.urls", namespace="events")),
]

sherpany/events/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from accounts.models import User


class Event(models.Model):
    creator = models.ForeignKey(User, related_name="events", on_delete=models.CASCADE)
    title = models.CharField(_("Title"), max_length=100)
    description = models.TextField(_("Description"))
    start_at = models.DateField(_("Start at"))

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-start_at", "-id")

    def __str__(self):
        return self.title

    @property
    def owner(self):
        return self.creator.email.split("@")[0]

    def is_owner(self, user) -> bool:
        """Check user is owner of event."""
        return self.creator == user

    def has_edit_permission(self, user) -> bool:
        """Check user has edit permission."""
        return self.is_owner(user)

    def is_participant(self, user) -> bool:
        """Check user is in participants"""
        return self.participants.filter(user=user).exists()

    def is_passed(self):
        today = timezone.now().date()
        return self.start_at <= today


class EventRSVP(models.Model):
    user = models.ForeignKey(User, related_name="rsvp", on_delete=models.CASCADE)
    event = models.ForeignKey(
        Event, related_name="participants", on_delete=models.CASCADE
    )

    class Meta:
        unique_together = [
            [
                "user",
                "event",
            ]
        ]

    def __str__(self):
        return f"{self.user.email}: {self.event.title}"

sherpany/events/forms.py
from django import forms
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from events.models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ("title", "description", "start_at")

    def clean_start_at(self):
        start_at = self.cleaned_data.get("start_at")
        today = timezone.now().date()
        if start_at <= today:
            raise forms.ValidationError(_("Start at must greater than today."))

        return start_at

sherpany/events/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from events.forms import EventForm
from events.models import Event, EventRSVP
from events.permissions import UserPermissionMixin


class BaseEventQueryMixin:
    queryset = Event.objects.select_related("creator").prefetch_related("participants")


class MyEventView(
    LoginRequiredMixin,
    BaseEventQueryMixin,
    ListView,
):
    """My event view."""

    model = Event
    template_name = "events/my_events.html"
    paginate_by = 10

    def get_queryset(self):
        """Override to filter queryset by logged in user."""
        queryset = super().get_queryset()
        return queryset.filter(creator=self.request.user)


class CreateUpdateEventView(
    UserPermissionMixin,
    SuccessMessageMixin,
    BaseEventQueryMixin,
    CreateView,
    UpdateView,
):
    "Create and update event view."
    form_class = EventForm
    template_name = "events/create_event.html"
    success_url = reverse_lazy("events:my_events")
    success_message = _("Event has been saved")

    def get_object(self, queryset=None):
        """Override to to support create and update."""
        try:
            return super(CreateUpdateEventView, self).get_object(queryset)
        except AttributeError:
            return None

    def form_valid(self, form):
        """Override to set creator as logged in user."""
        form.instance.creator = self.request.user
        return super().form_valid(form)


class DeleteEventView(
    UserPermissionMixin,
    BaseEventQueryMixin,
    DeleteView,
):
    "Delete event view."
    success_url = reverse_lazy("events:my_events")
    success_message = _("Event has been deleted")

    def delete(self, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(*args, **kwargs)


class DetailEventView(
    LoginRequiredMixin,
    BaseEventQueryMixin,
    DetailView,
):
    """Detail event view."""

    template_name = "events/detail_event.html"

    def get_context_data(self, **kwargs):
        """Override get_context_data to add is_participant flag."""
        context = super().get_context_data(**kwargs)
        instance = self.get_object()
        context.update(
            {
                "is_participant": instance.is_participant(self.request.user),
            }
        )
        return context


class PublicEventView(
    LoginRequiredMixin,
    BaseEventQueryMixin,
    ListView,
):
    """Public event view."""

    template_name = "events/public_events.html"
    paginate_by = 10


class ReserveEventView(
    LoginRequiredMixin,
    BaseEventQueryMixin,
    CreateView,
):
    """Reserve event view."""

    success_url = reverse_lazy("events:public_events")
    success_message = _("You have successfully reserved to the event")

    def post(self, request, pk):
        event = get_object_or_404(
            self.get_queryset(),
            id=pk,
        )
        if event.is_passed():
            messages.error(request, _("You can't do reservation to passed event."))

        elif event.is_owner(request.user):
            messages.error(request, _("You can't do reservation to your own event."))

        elif event.is_participant(request.user):
            messages.error(request, _("You already reserved this event."))

        else:
            EventRSVP.objects.create(user=request.user, event=event)
            messages.success(request, self.success_message)

        return redirect(self.success_url)


class WithdrawReservationEventView(
    LoginRequiredMixin,
    BaseEventQueryMixin,
    DeleteView,
):
    """Withdraw reservation event view."""

    success_url = reverse_lazy("events:public_events")
    success_message = _("You have successfully withdraw reservation to the event")

    def delete(self, *args, **kwargs):
        event = self.get_object()
        if not event.is_participant(self.request.user):
            return HttpResponseForbidden()

        event.participants.get(user=self.request.user).delete()
        messages.success(self.request, self.success_message)
        return redirect(self.success_url)

sherpany/events/templates/events/create_event.html
{% extends 'base.html' %}
{% block extra_css %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
{% endblock extra_css %}

{% block content %}
  <form action="{{request.path}}" method="POST">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit" class="btn btn-primary">Save</button>
  </form>
{% endblock content %}

{% block extra_js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $(document).ready(function(){
      $('#id_start_at').datepicker({
        format: 'yyyy-mm-dd',
        startDate: '+1d'
      });
    })
  </script>
{% endblock extra_js %}

sherpany/events/templates/events/detail_event.html
{% extends 'base.html' %}
{% block content %}
  <div class="input-group mb-3">
    <label for="">Title:</label>
    <p>{{object.title}}</p>
  </div>
  <div class="input-group mb-3">
    <label for="">Description:</label>
    <p>{{object.description|linebreaks}}</p>
  </div>
  <div class="input-group mb-3">
    <label for="">Start at:</label>
    <p>{{object.start_at|date}}</p>
  </div>
  {% if object.creator != request.user %}
    {% if not is_participant %}
      <a href="{% url 'events:reserve_event' event.id %}" confirm_message="Are you sure want to reservation to this event?" class="post_link">Reserve</a>
    {% else %}
      <a href="{% url 'events:withdraw_event_reservation' event.id %}" confirm_message="Are you sure want to withdraw reservation to this event?" class="post_link">Withdraw Reservation</a>
    {% endif %}
  {% else %}
    <a href="{% url 'events:update_event' event.id %}">Edit</a>
  {% endif %}
{% endblock content %}

sherpany/events/templates/events/my_events.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}

{% block content %}
  <hr>
  {% if object_list %}
  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th>Creator</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Start at</th>
      <th scope="col">Total Participants</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for event in object_list %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{event.owner}}</t>
      <td>{{ event.title }}</td>
      <td>{{ event.description }}</td>
      <td>{{ event.start_at }}</td>
      <td>{{ event.participants.count }}</td>
      <td>
        <a href="{% url 'events:update_event' event.id %}">Edit</a>
        <a href="{% url 'events:delete_event' event.id %}" confirm_message="Are you sure want to delete this event?" class="post_link">Delete</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
  </table>
  {% bootstrap_paginate page_obj %}
  {% else %}
    No events yet
  {% endif %}
{% endblock content %}

sherpany/events/templates/events/public_events.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}

{% block content %}
  <hr>
  {% if object_list %}
  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Start at</th>
      <th scope="col">Total Participants</th>
      <th scope="col">Owner</th>
    </tr>
  </thead>
  <tbody>
    {% for event in object_list %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td><a href="{% url 'events:detail_event' event.id%}">{{ event.title }}</a></td>
      <td>{{ event.description|linebreaks }}</td>
      <td>{{ event.start_at|date }}</td>
      <td>{{ event.participants.count }}</td>
      <td>{{ event.owner }}</td>
    </tr>
    {% endfor %}
  </tbody>
  </table>
  {% bootstrap_paginate page_obj %}
  {% else %}
    No events yet.
  {% endif %}

{% endblock content %}